### ISSUE TITLE
BDV->OMEZarr does not work correctly with time dimension

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#105]
When opening an ome.zarr volume with time dimension, e.g. https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/tczyx.ome.zarr it should add the scrollbar for the time axis. But it doesn't:
![image](https://user-images.githubusercontent.com/4263537/176425064-d6bfcf3b-d93d-4cc8-9f09-f0a4ffa2bf13.png)

(This is using the mobie-io version that's shipped with the latest MoBIE-beta)

**Comment by KateMoreva** [comment]
test **showTCZYX** 
`(OMEZarrS3Opener.readURL("https://s3.embl.de/i2k-2020/ngff-example-data/v0.4/tczyx.ome.zarr")` 
from the develop does open the timeline. 
![Uploading Screenshot 2022-06-29 at 22.50.59.png…]()
@constantinpape, could you please describe your actions in more detail?

**Comment by constantinpape** [comment]
I am opening it from Fiji, using the latest MoBIE-beta update site.
@tischi: the reason may be that you are not deploying the correct mobie.io there; I remember we had some confusion with the versioning of mobie.io when we looked at this yesterday morning.

**Comment by tischi** [comment]
Yes, could be, I can redeploy tomorrow using the latest mobie-io develop.

**Comment by tischi** [comment]
Done.

**Comment by constantinpape** [comment]
I have just tried on the latest mobie-beta, and the issue is still there.

**Comment by KateMoreva** [comment]
> I have just tried on the latest mobie-beta, and the issue is still there.

hm, I'll try to fix this tomorrow. I think it might be something on mobie-fiji side.

**Comment by constantinpape** [comment]
This issue is still there in the latest mobie-beta release.
